web_type : "chrome" # "chrome" or "firefox" or "edge"
LLM_TYPE : "openai" # openai

# LLM settings
# openai settings
is_azure : True
AZURE_OPENAI_ENDPOINT : ""
AZURE_OPENAI_KEY : ""
AZURE_OPENAI_API_VERSION : "2024-02-01"
AZURE_OPENAI_DALLE_ENDPOINT : ""
AZURE_OPENAI_DALLE_KEY : ""


OPENAI_API_KEY : ""
OPENAI_PROXY_URL : ""


# IMG Generator settings (if not set, it will use the openai settings)
IMG_GEN_TYPE : "dalle3" # "dalle3"
